# Generated by Django 4.1.4 on 2022-12-11 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("owner", models.CharField(max_length=250)),
                ("products_and_quantity", models.JSONField()),
                ("total_amount", models.CharField(max_length=20)),
                (
                    "order_state",
                    models.IntegerField(
                        choices=[
                            (0, "CARTED"),
                            (1, "PAID"),
                            (2, "COMPLETED"),
                            (3, "CANCELLED"),
                        ]
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Last update at"),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("prod_id", models.CharField(max_length=15)),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("owner", models.CharField(max_length=250)),
                ("labels", models.JSONField(null=True)),
                ("price", models.CharField(max_length=20)),
                ("quantity", models.IntegerField(default=1)),
                ("number_in_stock", models.IntegerField(default=0)),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Last update at"),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
    ]
