# Generated by Django 4.1.4 on 2022-12-12 22:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="number_in_stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(default=232332, max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=20)),
                ("quantity", models.IntegerField(default=1)),
                ("number_in_stock", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.product",
                    ),
                ),
            ],
        ),
    ]
